# Generated by Django 5.1.7 on 2025-03-31 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("sedan", "Седан"),
                    ("hatchback", "Хэтчбек"),
                    ("SUV", "Внедорожник"),
                    ("wagon", "Универсал"),
                    ("minivan", "Минивэн"),
                    ("pickup", "Пикап"),
                    ("coupe", "Купе"),
                    ("cabrio", "Кабриолет"),
                ],
                default="sedan",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="color",
            field=models.CharField(default="black", max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="drive_unit",
            field=models.CharField(
                choices=[("rear", "Задний"), ("front", "Передний"), ("full", "Полный")],
                default="full",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("gasoline", "Бензин"),
                    ("diesel", "Дизель"),
                    ("hybrid", "Гибрид"),
                    ("electro", "Электро"),
                ],
                default="gasoline",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="gearbox",
            field=models.CharField(
                choices=[
                    ("manual", "Механика"),
                    ("automatic", "Автомат"),
                    ("вариатор", "CVT"),
                    ("robot", "Робот"),
                ],
                default="automatic",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="mileage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="car",
            name="model",
            field=models.CharField(default="KIA", max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.IntegerField(default=100.0),
        ),
        migrations.AddField(
            model_name="car",
            name="volume",
            field=models.IntegerField(default=1.6),
        ),
        migrations.AddField(
            model_name="car",
            name="year",
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name="sale",
            name="car",
            field=models.ForeignKey(
                default="1", on_delete=django.db.models.deletion.CASCADE, to="main.car"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="client",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.client",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
