# Generated by Django 5.1.7 on 2025-03-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_car_body_type_car_color_car_drive_unit_car_fuel_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="volume",
            field=models.FloatField(default=1.6),
        ),
    ]
