# Generated by Django 5.1.7 on 2025-03-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_car_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.IntegerField(default=500000),
        ),
    ]
